spring:
  application:
    name: waiting-queue-scheduler
  server:
    port: 8081 # 로컬 실행을 위해 포트 번호는 waiting-queue-api와 다르게 설정

  data:
    redis:
      host: localhost
      port: 6379
      password: wq-redis
      database: 0
      timeout: 2s
#      lettuce: // lettuce pool 사용 시 주석 해제하여 사용할 것
#        pool:
#          enabled: true
#          max-active: 16
#          max-idle: 8
#          min-idle: 0
#          max-wait: 2s

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

waiting-queue:
  waiting-item:
    # waiting-item 초기화 여부
    # 실제 환경에서는 상품 서버로부터 카프카 메시지를 받아 대기열 상품을 관리하나
    # 해당 프로젝트에서는 테스트를 위해 스케쥴러 서버 실행 시 대기열 상품을 생성합니다.
    need-to-initialize: true
