spring:
  application:
    name: waiting-queue-api
  data:
    redis:
      host: localhost
      port: 6379
      password: wq-redis
      database: 0
      timeout: 2s
#      lettuce: // lettuce pool 사용 시 주석 해제하여 사용할 것
#        pool:
#          enabled: true
#          max-active: 16
#          max-idle: 8
#          min-idle: 0
#          max-wait: 2s

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
